[package]
name = "commitlint"
description = "A tool for linting conventional-commits commit messages"
version = "0.0.0"
license = "MIT OR Apache-2.0"
authors = ["Sven Lechner <SirWindfield@users.noreply.github.com>"]
edition = "2018"
